<template>
  <!-- The live region both enquiry forms use to report the outcome of a send.
       It stays mounted whatever the status so that screen readers announce the
       message when it appears; a region that is created at the same moment its
       text arrives is frequently missed.

       Success copy differs per form, so it comes in through the default slot;
       failure text is generated by the composable and passed as `message`. -->
  <div role="status" aria-live="polite" class="empty:hidden">
    <p
      v-if="status === 'success'"
      class="text-body rounded-lg border-l-4 border-primary bg-primary/5 px-5 py-4 text-text"
    >
      <slot />
    </p>
    <p
      v-else-if="status === 'error' && message"
      class="text-body rounded-lg border-l-4 border-secondary bg-secondary/5 px-5 py-4 text-text"
    >
      {{ message }}
    </p>
  </div>
</template>

<script setup>
defineProps({
  status: { type: String, required: true },
  message: { type: String, default: "" },
});
</script>
